### ISSUE TITLE
[Modal] callback method onHide() returns false but Dimmer is hidden

### ISSUE THREAD

**Issue by lubber-de** [fomantic/Fomantic-UI#215]
# Bug Report

## Description
If `onHide` for Modal returns false, the Modal stays open, but the dimmer hides

### Original SUI Issue
https://github.com/Semantic-Org/Semantic-UI/issues/4470
### Original SUI PR 
https://github.com/Semantic-Org/Semantic-UI/pull/5332

**Comment by lubber-de** [comment]
Mmh, i cannot reproduce it anymore using the given fiddle http://jsfiddle.net/81ejodv3/ from the Original Issue. It seems it was somehow already fixed in any SUI release in between

**Comment by luffyzc** [comment]
The issue is still reproducible as in http://jsfiddle.net/81ejodv3/,  clicking on the dimmer trigger the onHide handler which return false, but still close the modal

**Comment by lubber-de** [comment]
@luffyzc It is fixed since Fomantic-UI 2.7.0 😁  by #288 
See same example using FUI here http://jsfiddle.net/q8c5zn3m/
