### ISSUE TITLE
[API] Cannot delete element between two api call with form serialization

### ISSUE THREAD

**Issue by cmorin28** [fomantic/Fomantic-UI#2174]
# Bug Report
I use the API module to send a form with the "serializeForm" parameter. In my form, I use a "multiple" dropdown and when I send it twice (with less elements the second time), I find elements from the first send in the second.

## Steps to reproduce
1. Create form (in my case with a "multiple" dropdown)
2. Select two elements in the dropdown
3. Send the form via API module (with the "serializeForm" parameter)
4. Remove elements in the dropdown and select another
5. Send the form again via API

## Expected result
Have only the items selected each time

## Actual result
We have old selected values

## Testcase
https://jsfiddle.net/54mnafog/6/

## Investigations
Apparently, the "settings.data" variable is not cleared between API calls and "module.add.formData" ("serializeForm") merges old and new form data. I tried with empty "settings.defaultData" but this property does not seem to be used. 

## Version
2.8.8

**Comment by lubber-de** [comment]
This is fixed in the latest beta. We implemented an own version of  serializeObject  by #2047  and removed the dependency. This is now also fixing your issue 🙂 

Try the Nightly CDN, see your adjusted jsfiddle here
https://jsfiddle.net/lubber/05msby9h/

**Comment by cmorin28** [comment]
Sorry, but I still have the bug :'-(

Try to select three languages in your jsfiddle (English + French + Dutch), send, remove one and re-send... 
![image](https://user-images.githubusercontent.com/68468137/145250510-873e6fec-8466-4bba-85c3-c7ae2b0b2aaa.png)

**Comment by cmorin28** [comment]
Maybe I can make the change myself, but I don't understand why there is a merge between two calls

**Comment by lubber-de** [comment]
Indeed....i am reopening this

**Comment by cmorin28** [comment]
Thank you ! 😁

**Comment by cmorin28** [comment]
Sorry but the bug still exists: When you remove all values, the API module still sends the previous ones 😕.

**Comment by lubber-de** [comment]
> Sorry but the bug still exists: When you remove all values, the API module still sends the previous ones 😕.

Damn....missed that use case 🙄 . However, i think i fixed it properly now by #2181 
See https://jsfiddle.net/lubber/05msby9h/6/
