### ISSUE TITLE
[Form] Dynamically Removed Fields Still Throws Error in Console

### ISSUE THREAD

**Issue by KiddoV** [fomantic/Fomantic-UI#2577]
# Bug Report
Removing form field dynamically still getting error ``"Field identifier `field name` not found"``!!

## Steps to reproduce
https://jsfiddle.net/KiddoV/0wvgbe4q/35/
1. Open Fiddle!
2. Hit Remove Field button!
3. Hit Submit button!

## Expected result
Expecting no ERROR in console!!!

## Version
2.9.0

**Comment by prudho** [comment]
Thanks for your feedback. #2633 should fix this issue.

**Comment by KiddoV** [comment]
I am still getting this error on ``v2.9.3``.  When removing the field and hit submit.
https://jsfiddle.net/fgw1bqr0/3/

```console
<a class='gotoLine' href='#"Form:", "Field identifier field\-2 not found"'>"Form:", "Field identifier field\-2 not found"</a>
<a class='gotoLine' href='#"Form:", "Field identifier field\-2 not found"'>"Form:", "Field identifier field\-2 not found"</a>
```

**Comment by ko2in** [comment]
@KiddoV Because, you've removed the field from DOM node, but the form still inspect the node when you submitted the form.

Better use the ```fields``` property in form config and remove the relevant field after the element is removed from DOM.

Here's fiddle https://jsfiddle.net/ko2in/kd5pyb9f/6/

**Comment by KiddoV** [comment]
@ko2in but this approach would conflict the purpose of ``autoCheckRequired: true``. Also imagine that I have a lot of fields and keep repeating myself to define ``empty`` validation for each field.

Also @prudho confirmed this is a bug and already had a fixed on https://github.com/fomantic/Fomantic-UI/pull/2633, so I would expect some changes here!

**Comment by ko2in** [comment]
Hmm. You're right. It looks strange. I took a quick glance, and this fix already included in the latest build.

Only @prudho version works.

**Comment by KiddoV** [comment]
Thank you!
