### ISSUE TITLE
[checkbox] Read-only checkbox state must not be changeable from UI

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2812]
# Bug Report

## Steps to reproduce
1. https://jsfiddle.net/4kuejywb/1/
2. click first checbox, press tab and then space key
3. notice, the second/read-only checkbox is changed

## Expected result

The state cannot be changed by mouse nor keyboard.

See https://stackoverflow.com/questions/155291/can-html-checkboxes-be-set-to-readonly for read-only "state"/"value" terminilogy.

Fomantic-UI docs - https://fomantic-ui.com/modules/checkbox.html#read-only - say "state" explicitly, thus I expect every checkbox/radio initialized like `$('.ui.checkbox').checkbox()` to be truly read-only.

## Version

latest

**Comment by lubber-de** [comment]
Fixed by https://github.com/fomantic/Fomantic-UI/pull/2813
See your adjusted jsfiddle here https://jsfiddle.net/lubber/xud45evh/

**Comment by mvorisek** [comment]
I am reopening this issue as #2813 did not fixed `radio`.

Steps to reproduce:
1. open https://dev.atk4.org/demos/form-control/input2.php
2. click first "one" in "Radio" section
3. press "tab" key - this will move you to a readonly radio group
4. press "up" key and notice the radio selection has changed

**Comment by lubber-de** [comment]
Fixed by #3003
