### ISSUE TITLE
[Massage] Not show error on safari

### ISSUE THREAD

**Issue by apple-idn** [fomantic/Fomantic-UI#557]
# Bug Report

## Steps to reproduce
1.if error on first modal massage error not show on Safari
2.when modal close and open again modal (tada error now show)
3.this only problem on safari browser

## Expected result
![image](https://user-images.githubusercontent.com/33564576/54082350-2a242500-434f-11e9-81e9-e5d1d80e0087.png)

## Actual result
![image](https://user-images.githubusercontent.com/33564576/54082354-4aec7a80-434f-11e9-8710-85babb57e7dc.png)

## Screenshot (when possible)
![]()

## Version
2.7.2

**Comment by lubber-de** [comment]
Fixed by #558 
See https://jsfiddle.net/43kLfupd/5/

**Comment by apple-idn** [comment]
@lubber-de it’s not FIXED,this happens if I enter form on modal

**Comment by lubber-de** [comment]
@apple-idn could you adjust or create a fiddle please then?

**Comment by lubber-de** [comment]
@apple-idn  I just changed the fiddle and #558  also fixes it when the form is used in modal.
Could you please test (before complaining...:wink:)
https://jsfiddle.net/srqh27go/

**Comment by lubber-de** [comment]
Here is a screenshot video using macOS Mojave and Safari 12 where it's not working as expected using the above mentioned jsfiddle
![safari_empty](https://user-images.githubusercontent.com/18379884/54086531-7b7de580-434a-11e9-98fa-7a34be802e15.gif)

**Comment by apple-idn** [comment]
@lubber-de, thanks very much to attention but well without add css this not fixed 😂😂**(fomantic ui standard)** why that??? only not show first open , and this **fixed if add** .ui.form .error.message:empty { display: none; } style from @lubber-de , 👌🏻😊 thanks very much
