### ISSUE TITLE
Positioning issue of floating label with pointing menu

### ISSUE THREAD

**Issue by aardbol** [fomantic/Fomantic-UI#668]
# Bug Report
Positioning of floating label with pointing menu is not optimal

## Steps to reproduce
See fiddle

## Expected result
The floating label should be better positioned with pointing menus

## Actual result
Positioning is too high

## Testcase

https://jsfiddle.net/kswyvoab/

## Screenshot (when possible)
Normal menu
![Screenshot_20190415_084129](https://user-images.githubusercontent.com/14614620/56112112-5c323380-5f5a-11e9-8538-77a7c9985a48.png)

Pointing menu
![Screenshot_20190415_084111](https://user-images.githubusercontent.com/14614620/56112119-5fc5ba80-5f5a-11e9-9baf-c5dba7c84f78.png)

## Version
2.7.2

**Comment by lubber-de** [comment]
Fixed by #669 
See your adjusted example here https://jsfiddle.net/gv2br0zu/

**Comment by IsaakGroepT** [comment]
Thanks for the fix, but there's still quite a lot of whitespace between the menu item and the label, so the appearance is still not quite optimal in my opinion. I tweaked the margins a bit further and margin-top: 1em seems to be more attractive

**Comment by lubber-de** [comment]
Even, if I agree it looks a unusual, the related fix corrects a logical issue leaving the floating label at the same consistent position as in the other menu variants now. Just because secondary pointing doesn't have a top border, it looks different, but the label is still in the same position as in the other menu variants now. 
Changing the position only for this menu variant would be an enhancement and as the floating label can also be positioned at the bottom, this also has to be considered and adjustments would be special to secondary pointing menus only.
For now, I suggest you set additional negative margin in your own overrides. You are welcome to provide another PR with any margin enhancements 😉

**Comment by IsaakGroepT** [comment]
Cool, my first PR! I'll investigate! :)
