### ISSUE TITLE
[Calendar] breaks dates that entered from the keyboard

### ISSUE THREAD

**Issue by tstar** [fomantic/Fomantic-UI#829]
# Bug Report
The calendar breaks dates that entered from the keyboard, it changes the day and month. The option monthFirst: false does not help. I'm not sure that the defined formatter makes sense for this bug, but I faced it using formatter.
PS: It is better to have the possibility to make custom date parse function like formatter.
## Steps to reproduce
1. Open Fomantic-UI Calendar -> Example -> Custom format page https://fomantic-ui.com/modules/calendar.html#custom-format
2. Enter from the keyboard 1/8/2012
## Expected result
1/8/2012
## Actual result
8/1/2012
## Version
2.7.6

**Comment by brunotourinho** [comment]
found this error today, while trying to apply jquery.inputmask to a field.

**Comment by tstar** [comment]
The issue present in version 2.7.8 :(

**Comment by prudho** [comment]
Latest PR #995 should fix this issue.

Sorry to be so long, but handling dates is Javascript is horrible...

**Comment by brunotourinho** [comment]
Yay! Thank you!

**Comment by Raoniw** [comment]
I'm still having this problem in the latest version of this library. The linked fix doesn't appear in the code anymore.

**Comment by ko2in** [comment]
@Raoniw I tested with Chrome (Version 86.0.4240.75) and latest FUI and I can't reproduce it.

![FUI-Calendar](https://user-images.githubusercontent.com/930315/95988980-ab0ea100-0e4f-11eb-8e02-1a93de85e8f0.gif)

See here (https://jsfiddle.net/ko2in/gn801bzj/).

**Comment by Raoniw** [comment]
@ko2in i still have the problem in your jsfiddle when using the date 1-5-2020 see:

![example](https://user-images.githubusercontent.com/9072792/95990779-3b3aef00-0e2c-11eb-956b-c4ec3a9a7773.gif)

**Comment by Raoniw** [comment]
When using this version with the altered calendar.js it works but this is not the current code from this library.

**Comment by ko2in** [comment]
The fiddle (https://jsfiddle.net/9caf67pv/) mentioned by @lubber-de in this PR #1004 works.

Look like this was modified again and stop working with `dd-mm-yyyy` format on Chrome. There is two different [version](https://github.com/fomantic/Fomantic-UI/pull/1004/files/a8cc9a3c424d587adaf30ed89eea6af975063fdf) from PR #1004 and the current [release](https://github.com/fomantic/Fomantic-UI/blob/develop/src/definitions/modules/calendar.js#L1474).

**Comment by lubber-de** [comment]
@Raoniw It was related to your single digit entry. If you would have entered the month as double digits it should have worked.
Anyway, i fixed it for the current codebase by  #1706 
I added the fix to @ko2in jsfiddle here https://jsfiddle.net/lubber/67d2hsrw/
