### ISSUE TITLE
[Menu][Grouped icons] grouped icons in submenu not behave like simple icon

### ISSUE THREAD

**Issue by Ikaer** [fomantic/Fomantic-UI#936]
# Bug Report

## Steps to reproduce
1. https://jsfiddle.net/b5og0sxL/
2. Grouped icons in first menu are ok.
3. Grouped icons in sub menu "Actions" do not behave like simple icon 

## Expected result
- Position should be left.
- Corner icons should be respected

## Actual result
- Position is right instead of left.
- Corner icon rules are not respected.

## Testcase
https://jsfiddle.net/b5og0sxL/

## Screenshot (when possible)
![image](https://user-images.githubusercontent.com/7936075/63002280-d970a500-be75-11e9-83ba-84c299cbf1f1.png)

## Version
2.7.7

**Comment by Ikaer** [comment]
I've temporarly fix it with following css rules:
https://jsfiddle.net/b5og0sxL/1/

**Comment by Ikaer** [comment]
Some other issues with grouped icons and lists. Do you prefer I open another issue ?

https://jsfiddle.net/cav3wsqf/

On grouped icons:
- normal color is incorrect.
- hover color is incorrect.
- right margin is incorrect.

Fixed by adding those rules:
https://jsfiddle.net/cav3wsqf/1/

**Comment by hammy2899** [comment]
@Ikaer Yes open another issue because they seem unrelated to this one.

**Comment by lubber-de** [comment]
Fixed by #1536  Sorry, it took so long

**Comment by Ikaer** [comment]
Hi, 

Sorry to reopen this, but we still have an issue with the grouped icons and menu when those icons are on left side. The padding is not applied between the icons and the text.

TestCase
https://jsfiddle.net/fndmr6os/

Screenshots
![image](https://user-images.githubusercontent.com/7936075/99063893-7c4a2e80-25a5-11eb-8eed-f93b50c2ec8c.png)
![image](https://user-images.githubusercontent.com/7936075/99063906-81a77900-25a5-11eb-8fd5-2ed9141a0a13.png)

Version
2.7.8

**Comment by lubber-de** [comment]
> Sorry to reopen this, but we still have an issue with the grouped icons and menu when those icons are on left side. The padding is not applied between the icons and the text.

Fixed by #1766
